import type { Metadata } from "next";
import { Suspense } from "react";
import { Inter } from "next/font/google";
import Header from "@/components/header";
import Footer from "@/components/footer";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Shop Bogdan",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Suspense fallback={<div>Loading page...</div>}>
          <main className="min-h-dvh flex flex-col">
            <Header />
            {children}
            <Footer />
          </main>
        </Suspense>
      </body>
    </html>
  );
}
