import type { Metadata } from "next";
import { Inter } from "next/font/google";
import NextTopLoader from 'nextjs-toploader';
import ButtonUp from "@/components/ui/ButtonUp";
import Header from "@/components/header";
import Footer from "@/components/footer";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Shop Bogdan",
  description: "Generated by create next app",
  // openGraph: {
  //   images: '/products/1.png',
  // },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextTopLoader color="#16A34A" height={3} showSpinner={false} shadow={false} />
        <ButtonUp />
        <Header />
        <main className="min-h-[calc(100dvh_-_210px)] flex flex-col pb-4">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
